PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS metadata(key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS objects(id TEXT PRIMARY KEY, type TEXT NOT NULL, head INTEGER NOT NULL, owner TEXT NOT NULL, visibility TEXT NOT NULL CHECK(visibility IN ('private','shared')));
CREATE TABLE IF NOT EXISTS blobs(hash TEXT PRIMARY KEY CHECK(length(hash)=64), bytes INTEGER NOT NULL CHECK(bytes>=0));
CREATE TABLE IF NOT EXISTS object_revisions(object_id TEXT NOT NULL REFERENCES objects(id), revision INTEGER NOT NULL CHECK(revision>0), status TEXT NOT NULL, recorded_at TEXT NOT NULL, envelope TEXT NOT NULL, PRIMARY KEY(object_id,revision));
CREATE TABLE IF NOT EXISTS revision_blobs(object_id TEXT NOT NULL,revision INTEGER NOT NULL,hash TEXT NOT NULL REFERENCES blobs(hash),PRIMARY KEY(object_id,revision,hash),FOREIGN KEY(object_id,revision) REFERENCES object_revisions(object_id,revision));
CREATE TABLE IF NOT EXISTS object_links(object_id TEXT NOT NULL,revision INTEGER NOT NULL,field TEXT NOT NULL,target_id TEXT NOT NULL,target_revision INTEGER NOT NULL,PRIMARY KEY(object_id,revision,field),FOREIGN KEY(object_id,revision) REFERENCES object_revisions(object_id,revision),FOREIGN KEY(target_id,target_revision) REFERENCES object_revisions(object_id,revision));
CREATE TABLE IF NOT EXISTS events(seq INTEGER PRIMARY KEY AUTOINCREMENT,event_id TEXT NOT NULL UNIQUE,object_id TEXT REFERENCES objects(id),revision INTEGER,type TEXT NOT NULL,payload TEXT NOT NULL,observed_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS operations(operation_id TEXT PRIMARY KEY,request_hash TEXT NOT NULL,actor TEXT NOT NULL,response TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS command_operations(operation_id TEXT PRIMARY KEY,request_hash TEXT NOT NULL,actor TEXT NOT NULL,action TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN('pending','done')),response TEXT,recorded_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS outbox(seq INTEGER PRIMARY KEY REFERENCES events(seq),object_id TEXT NOT NULL REFERENCES objects(id),revision INTEGER NOT NULL,done INTEGER NOT NULL DEFAULT 0 CHECK(done IN(0,1)));
CREATE TABLE IF NOT EXISTS materializations(name TEXT PRIMARY KEY,watermark INTEGER NOT NULL DEFAULT 0);
CREATE VIRTUAL TABLE IF NOT EXISTS search_docs USING fts5(object_id UNINDEXED,revision UNINDEXED,text);
CREATE TABLE IF NOT EXISTS relations(id TEXT NOT NULL,revision INTEGER NOT NULL,source TEXT NOT NULL REFERENCES objects(id),target TEXT NOT NULL REFERENCES objects(id),kind TEXT NOT NULL,owner TEXT NOT NULL,PRIMARY KEY(id,revision));
CREATE TABLE IF NOT EXISTS source_locations(id TEXT PRIMARY KEY,root_id TEXT NOT NULL,locator TEXT NOT NULL,hash TEXT,access TEXT NOT NULL CHECK(access='read-only'));
CREATE TABLE IF NOT EXISTS host_events(event_id TEXT PRIMARY KEY,source_host TEXT NOT NULL,host_epoch TEXT NOT NULL,source_seq INTEGER NOT NULL CHECK(source_seq>0),payload TEXT NOT NULL,request_hash TEXT NOT NULL,UNIQUE(source_host,host_epoch,source_seq));
CREATE TABLE IF NOT EXISTS host_watermarks(source_host TEXT NOT NULL,host_epoch TEXT NOT NULL,contiguous INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(source_host,host_epoch));
CREATE TABLE IF NOT EXISTS validation_obligations(task_id TEXT NOT NULL REFERENCES objects(id),task_revision INTEGER NOT NULL,property TEXT NOT NULL,PRIMARY KEY(task_id,task_revision,property));
CREATE TABLE IF NOT EXISTS validations(id TEXT PRIMARY KEY REFERENCES objects(id),task_id TEXT NOT NULL REFERENCES objects(id),task_revision INTEGER NOT NULL,property TEXT NOT NULL,result TEXT NOT NULL CHECK(result IN('pass','fail','inconclusive')),environment_hash TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS jobs(id TEXT PRIMARY KEY,kind TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN('pending','running','done','failed')),fence INTEGER NOT NULL DEFAULT 0,lease_until REAL,payload TEXT NOT NULL);
PRAGMA user_version=1;
