/* Faceted directory: references can repeat; records and source bodies do not. */
let observeSnapshot=null,observeBusy=false,catalogSnapshot=null,catalogSelection=null,catalogSequence=0;
let displayLanguage='zh';try{displayLanguage=localStorage.getItem('uacf.displayLanguage')==='en'?'en':'zh'}catch{}
const vocabulary={title:['资料库','Library'],language:['显示语言','Language'],search:['搜索标题、关键词或标签','Search titles, keywords or tags'],searchButton:['搜索','Search'],update:['更新目录','Update catalogue'],work:['任务与引用记录','Tasks and references'],history:['修订记录','Revisions'],system:['部署记录','Deployments'],advanced:['维护与工程控制','Engineering'],detail:['查看依据与字段','Evidence and fields'],more:['打开工程记录','Open engineering record']};
const tr=k=>vocabulary[k]?.[displayLanguage==='en'?1:0]||k,ct=(zh,en)=>displayLanguage==='en'?en:zh;
function make(tag,text,parent){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(parent)parent.append(n);return n}
function applyDisplayLanguage(){document.documentElement.lang=displayLanguage==='en'?'en':'zh-CN';document.querySelectorAll('[data-i18n]').forEach(n=>n.textContent=tr(n.dataset.i18n));document.querySelectorAll('[data-zh]').forEach(n=>n.textContent=n.dataset[displayLanguage==='en'?'en':'zh']);$('displayLanguage').value=displayLanguage;try{localStorage.setItem('uacf.displayLanguage',displayLanguage)}catch{};if(catalogSnapshot)renderCatalog();else show('observeState',ct('登录后显示库总览，无需先搜索。','Sign in to browse without searching.'))}
function basisBox(parent,value){const d=make('details',undefined,parent);make('summary',tr('detail'),d);make('pre',JSON.stringify(value,null,2),d)}
function openCanonical(id){const b=make('button',tr('more'));b.onclick=guarded(async()=>{select((await api('get',{object_id:id})).object);$('engineering').open=true;$('detail').scrollIntoView({block:'center'})});return b}
const axisNames={project_domain:['项目自身问题','Project problems'],ai_execution:['AI 执行错误','AI execution errors'],runtime:['运行环境观察','Runtime observations'],policy_boundary:['正常拒绝与权限边界','Normal refusals and boundaries'],unclassified:['尚未判断问题归类','Classification pending']};
const assessmentNames={observed:['有实测依据','Observed'],provisional:['临时评审，待确认','Provisional'],boundary:['边界记录，不计缺陷','Boundary, not a defect'],not_reviewed:['未复核','Not reviewed']};
const axes=c=>c.axes.map(x=>axisNames[x]?.[displayLanguage==='en'?1:0]||x).join(' · ');
function renderCatalog(){const r=catalogSnapshot,c=r.counts;show('observeState',ct(`${c.archive_conversations} 个旧对话 · ${c.projects} 个项目记录 · ${c.issue_records} 条问题/边界记录`,`${c.archive_conversations} conversations · ${c.projects} projects · ${c.issue_records} issue/boundary records`));show('observeHint',ct('目录可以展开、收起。同一资料能出现在多个入口；先读目录，再按需读原文。','Expand directories and follow references; source bodies load only on demand.'));
 const tree=$('catalogTree'),openStates=new Map([...tree.querySelectorAll('details')].map(d=>[d.dataset.key,d.open]));tree.replaceChildren();
 for(const root of r.roots){const d=make('details',undefined,tree);d.dataset.key=root.key;d.open=openStates.has(root.key)?openStates.get(root.key):['projects','issues','archive'].includes(root.key);make('summary',root.title+' · '+root.count,d).title=root.note;for(const child of root.children||[]){const b=make('button',undefined,d);b.type='button';b.className='catalog-branch'+(catalogSelection?.key===child.key?' active':'');make('span',child.title,b);make('span',String(child.count),b).className='catalog-count';b.title=child.note;b.onclick=()=>loadBranch(child.key,child.title)}}
 const summary=$('catalogSummary');summary.replaceChildren();const metrics=make('div',undefined,summary);metrics.className='catalog-metrics';for(const [value,title] of [[c.archive_conversations,ct('已归档对话','Archived conversations')],[r.archive_coverage?.nodes??'—',ct('已存储消息/结构节点','Stored messages / structure nodes')],[c.selected_conversations,ct('已建立选用片段的对话','Conversations with selected spans')]]){const m=make('div',undefined,metrics);m.className='catalog-metric';make('strong',String(value),m);make('span',title,m)}
 const coverage=r.archive_coverage;if(coverage){make('h3',ct('当前来源处理状态','Current source processing'),summary);const table=make('table',undefined,summary);const rows=[[ct('语义候选来源','Semantic candidate sources'),String(coverage.semantic_candidate_sources??0),ct(`独立语义验收 ${coverage.independent_semantic_accepted??0}；候选不等于验收`,'Candidates are not independent acceptance')],[ct('归档与结构索引','Archive and structure index'),`${coverage.conversations} 对话 · ${coverage.messages} 消息 · ${coverage.nodes} 节点`,coverage.structure_status==='complete_for_frozen_shards'?ct(`冻结范围 ${coverage.completed_shards}/${coverage.declared_shards} 个分片已完成`,'All frozen shards complete'):ct('冻结范围尚未完成','Frozen scope incomplete')],[ct('附件引用定位','Attachment reference mapping'),`${coverage.resolved_attachment_refs}/${coverage.attachment_refs}`,ct(`${coverage.unresolved_attachment_refs} 次引用尚未定位`,'Unresolved references remain')],[ct('附件内容读取','Attachment bodies read'),String(coverage.attachment_bodies_read),ct('只读了这些样本；没有完成全量附件理解','Samples only; full attachment understanding incomplete')],[ct('全库语义分类与验收','Full semantic classification and acceptance'),ct('未完成','Incomplete'),ct('语义验收须以当前任务冻结范围及实际证据核对；选用片段数量不能代替验收','Check the current task scope and evidence; selected span counts are not semantic acceptance')]];for(const row of rows){const tr=make('tr',undefined,table);for(const value of row)make('td',value,tr)}make('p',ct('依据：当前库的冻结范围、检查点与来源回执。没有来源时数量为0；归档不等于语义理解。','Based on the current store, frozen scopes and receipts. An empty source store has zero sources; archival is not semantic understanding.'),summary)}
 if(catalogSelection)return;
 const box=$('catalogResults');box.replaceChildren();make('h3',ct('目前整理到哪一步','What has been organised'),box);const t=make('table',undefined,box);t.className='catalog-axis-table';const head=make('tr',undefined,t);for(const title of [ct('入口','View'),ct('数量','Count'),ct('整理程度','Coverage')])make('th',title,head);
 for(const row of [[ct('项目与归属','Projects and membership'),`${c.projects} / ${c.semantic_memberships}`,ct('归属按真实记录核对；同名项目保留独立身份。','Check recorded membership; same-name projects retain distinct identities.')],[ct('项目自身问题','Project problems'),c.project_issue_records,ct('0条表示尚未登记，不表示没有问题。','Zero means unregistered, not absent.')],[ct('AI执行错误','AI execution errors'),ct(`${c.ai_observed_issues} 实测 / ${c.ai_provisional_issues} 待确认`,`${c.ai_observed_issues} observed / ${c.ai_provisional_issues} provisional`),ct('候选与实测分开；正常拒绝不算缺陷。','Provisional and observed cases are separate; refusals are not defects.')],[ct('选用片段','Selected spans'),`${c.selected_conversations} / ${c.archive_conversations}`,ct('这是选用范围，不是整理完成率；其余对话也已归档。','Reuse selection, not completion; other conversations are archived too.')]]){const tr=make('tr',undefined,t);for(const text of row)make('td',String(text),tr)}make('p',ct('左侧按项目、问题或标签进入。日志不会一次性铺开。','Choose projects, issues or tags on the left; logs are not expanded all at once.'),box);
}
async function loadBranch(key,title,offset=0,query='',scope='metadata'){const ticket=++catalogSequence;catalogSelection={key,title,offset,query,scope};$('catalogDetail').replaceChildren();show('catalogResults',ct('正在读取目录…','Loading…'));try{const r=await api('catalog',{mode:'children',key,offset,limit:25,query,scope});if(ticket!==catalogSequence)return;renderItems(r,title);renderCatalog()}catch(e){if(ticket===catalogSequence)show('catalogResults',e.message)}}
function renderItems(r,title){const box=$('catalogResults');box.replaceChildren();make('h3',title+' · '+r.total,box);if(!r.items.length)make('p',ct('这个入口还没有登记记录。','No registered records in this view.'),box);const groups=new Map();for(const entry of r.items){const name=entry.kind==='conversation'?ct('对话目录','Conversations'):entry.type_label;let parent=groups.get(name);if(!parent){parent=make('details',undefined,box);parent.open=true;make('summary',name,parent);groups.set(name,parent)}const row=make('div',undefined,parent);row.className='catalog-row';const b=make('button',entry.title+(entry.type==='Project'?' · '+entry.id.slice(0,8):''),row);b.title=entry.title;b.onclick=()=>entry.type==='Project'?loadBranch('project:'+entry.id,entry.title):openEntry(entry);if(entry.classification){const cl=entry.classification;make('p',axes(cl)+' · '+(assessmentNames[cl.assessment]?.[displayLanguage==='en'?1:0]||cl.assessment),row);if(cl.tags.length)make('p',cl.tags.join(' · '),row)}else make('p',ct(entry.processing==='selected'?'有选中片段 · 点击展开消息目录':'已归档 · 未建立选用片段 · 点击展开消息目录','Open message directory'),row)}
 const paging=make('div',undefined,box);for(const [label,offset,disabled] of [[ct('上一页','Previous'),Math.max(0,r.offset-25),r.offset===0],[ct('下一页','Next'),r.offset+25,r.offset+25>=r.total]]){const b=make('button',label,paging);b.disabled=disabled;b.onclick=()=>loadBranch(catalogSelection.key,catalogSelection.title,offset,catalogSelection.query,catalogSelection.scope)}make('p',ct(`目录第 ${r.total?r.offset+1:0}—${Math.min(r.offset+25,r.total)} 条；尚未加载正文。`,`Directory rows ${r.total?r.offset+1:0}–${Math.min(r.offset+25,r.total)}; bodies are not loaded.`),box)}
async function openEntry(entry){const ticket=++catalogSequence,box=$('catalogDetail');box.replaceChildren();box.className='catalog-drawer';make('h3',entry.title,box);try{if(entry.kind==='conversation'){await messageDirectory(entry,0,ticket);return}const r=await api('catalog',{mode:'detail',key:entry.id});if(ticket!==catalogSequence)return;const cl=r.item.classification;if(['FailureCase','FailurePattern'].includes(r.item.type)){make('p',ct('问题层面：','Issue layer: ')+axes(cl),box);if(cl.basis)make('p',ct('划分依据：','Basis: ')+cl.basis,box);make('p',ct('根因记录：','Root cause: ')+cl.root_cause,box)}const p=r.object.payload;for(const key of ['goal','lesson','summary','purpose'])if(p[key])make('p',p[key],box);if(p.observation){const obs=p.observation;make('h4',ct('这条回执记录了什么','What this receipt records'),box);if(obs.method==='native_DSH_two_rounds_with_independent_stdout_comparison'){make('p',ct('AOE4两轮真实工具调用与独立检查。执行时Task @','Real AOE4 calls and independent checks. Executed Task @')+obs.task_revision+' · '+obs.result,box);make('p',ct('已知usage折算：','Known usage-based cost: ')+(obs.known_usage_cost_micro/1000000)+ct('元；未知费用锁定：',' CNY; unknown cost locked: ')+(obs.unknown_cost_locked_micro/1000000)+ct('元。',' CNY.'),box);make('p',obs.correction,box)}else if(obs.method==='actual_owner_provider_inspection'){make('p',obs.provider+' / '+obs.model+' · '+obs.checked_at,box);make('p',ct('这是当时调用前的核验；不表示当前价格、能力或授权仍然有效。','Historical preflight does not establish current price, capability or authorisation.'),box)}else if(obs.result)make('p',String(obs.result),box)}for(const tag of cl.tags){const b=make('button',tag,box);b.onclick=()=>loadBranch('tag:'+tag,tag)}const refs=make('details',undefined,box);make('summary',ct('相关记录与依据','References')+' · '+r.references.length,refs);for(const ref of r.references){const b=make('button',ref.title,refs);b.onclick=()=>openEntry({kind:'object',id:ref.id,title:ref.title})}const loc=p.locator;if(loc?.archive_plan){const b=make('button',ct('展开原始对话目录','Open original conversation'),box);b.onclick=()=>openEntry({kind:'conversation',title:entry.title,locator:{plan_id:loc.archive_plan,member:loc.member,ordinal:loc.ordinal}})}basisBox(box,{id:r.item.id,revision:r.item.revision,status:r.item.status,classification:cl,payload:p});box.append(openCanonical(entry.id));box.scrollIntoView({block:'nearest'})}catch(e){if(ticket===catalogSequence)make('p',e.message,box)}}
async function messageDirectory(entry,offset,ticket){const r=await api('catalog',{mode:'messages',locator:entry.locator,offset,limit:20});if(ticket!==catalogSequence)return;const box=$('catalogDetail');box.replaceChildren();make('h3',entry.title,box);make('p',ct(`${r.total} 个消息/结构节点；点击一条才读取原文。`,`${r.total} message/structure nodes; open one to load source.`),box);for(const msg of r.items){const d=make('details',undefined,box);make('summary',(msg.detail.role||msg.detail.speaker||'消息/结构节点')+' · '+msg.id.slice(0,12),d);let loaded=false;d.addEventListener('toggle',async()=>{if(!d.open||loaded)return;loaded=true;try{const v=await api('catalog',{mode:'message',locator:msg.locator});const content=v.record.message?.content||v.record;make('pre',typeof content==='string'?content:JSON.stringify(content,null,2),d)}catch(e){loaded=false;make('p',e.message,d)}})}for(const [text,next,disabled] of [[ct('上一组','Previous messages'),Math.max(0,offset-20),offset===0],[ct('下一组','Next messages'),offset+20,offset+20>=r.total]]){const b=make('button',text,box);b.disabled=disabled;b.onclick=()=>messageDirectory(entry,next,ticket)}}
async function refreshObserve(force=false){if(!browserAuthenticated||observeBusy)return;observeBusy=true;try{const r=await api('catalog',{});if(force||!catalogSnapshot||catalogSnapshot.commit_seq!==r.commit_seq){catalogSnapshot=r;observeSnapshot={commit_seq:r.commit_seq};renderCatalog();if(catalogSelection)await loadBranch(catalogSelection.key,catalogSelection.title,catalogSelection.offset,catalogSelection.query,catalogSelection.scope)}}catch(e){show('observeState',e.message);throw e}finally{observeBusy=false}}
for(const [id,field] of [['observeWork','work_and_use'],['observeHistory','history'],['observeSystem','system_updates']]){$(id).closest('details').addEventListener('toggle',async e=>{if(!e.target.open||!browserAuthenticated)return;try{const r=await api('observatory',{limit:1}),box=$(id);box.replaceChildren();for(const row of r[field]||[]){const sub=make('details',undefined,box);make('summary',row.payload?.goal||row.type||row.identity||row.id,sub);basisBox(sub,row)}}catch(err){show(id,err.message)}})}
$('displayLanguage').onchange=()=>{displayLanguage=$('displayLanguage').value;applyDisplayLanguage()};$('observeRefresh').onclick=()=>refreshObserve(true);$('catalogSearchForm').onsubmit=e=>{e.preventDefault();const q=$('observeQuery').value.trim();if(!q){catalogSelection=null;$('catalogDetail').replaceChildren();renderCatalog();return}loadBranch('',ct('搜索结果','Search results'),0,q,$('catalogScope').value)};
const baseRefresh=refresh;refresh=async()=>{await baseRefresh();await refreshObserve(true)};setInterval(()=>{if(!document.hidden)refreshObserve(false).catch(()=>{})},15000);window.addEventListener('focus',()=>refreshObserve(false).catch(()=>{}));applyDisplayLanguage();
