/* Shared work update controls, not a second historical import database. */
const learningBox=document.createElement('section');learningBox.id='learningConsole';
learningBox.innerHTML='<h2>工作经验持续更新</h2><p>历史候选和新工作共用队列。机制关系是待审比较；只有注册验证器能提供硬规则验收。原资产与来源保留。</p><button id="learningConfigure">启用既有工作更新链</button><button id="learningQueue100">加入前100个现有来源</button><button id="learningQueueAll">加入全部现有候选来源</button><label>本次处理上限 <input id="learningCount" type="number" value="100" min="1" max="10000"></label><button id="learningStart">启动自动比较与更新</button><button id="learningPause">暂停新增调用</button><button id="learningRefresh">刷新更新状态</button><pre id="learningStatus"></pre><details><summary>特殊问题的人工干预</summary><p>未知调用先对账；已结算失败复用原回执。不会因刷新或重复入队重发模型。</p><label>任务回执 JSON <textarea id="learningManual"></textarea></label><button id="learningSubmit">提交已核对的比较结果</button></details>';
$('projectExecution').after(learningBox);
async function learningLoad(){if(!browserAuthenticated)return;const r=await api('learning_status');$('learningStatus').textContent=JSON.stringify({total:r.total,counts:r.counts,worker_alive:r.worker_alive,route:r.route,native_work_default:r.native_work_default,policy:r.policy?.ref,needs_review:r.jobs.filter(x=>x.state==='needs_review'||x.state==='dispatched')},null,2);$('learningStart').disabled=r.worker_alive;}
$('learningConfigure').onclick=guarded(async()=>{await api('learning_configure',{authorization:'当前用户明确要求：通用工作持续学习，重要纠错增量记录，短日常按节点聚合；保留历史，候选不能自行升级为硬规则。'});await learningLoad()});
async function learningQueue(count){const r=await api('learning_sources');const rows=r.rows.slice(0,count);for(let i=0;i<rows.length;i+=100)await api('learning_enqueue',{card_refs:rows.slice(i,i+100).map(x=>x.ref)});await learningLoad();}
$('learningQueue100').onclick=guarded(()=>learningQueue(100));$('learningQueueAll').onclick=guarded(()=>learningQueue(Infinity));
$('learningStart').onclick=guarded(async()=>{await api('learning_start',{count:Number($('learningCount').value)});await learningLoad()});$('learningPause').onclick=guarded(async()=>{await api('learning_pause');await learningLoad()});$('learningRefresh').onclick=guarded(learningLoad);
$('learningSubmit').onclick=guarded(async()=>{await api('learning_mark',JSON.parse($('learningManual').value));await learningLoad()});setInterval(()=>{if(browserAuthenticated&&!document.hidden)learningLoad().catch(()=>{})},10000);
const learningChecks=document.createElement('div');learningChecks.innerHTML='<button id="learningGuards">注册并测试硬规则</button><label>验收Task UUID <input id="learningVerifyTask"></label><button id="learningAcceptanceRead">读取冻结验收范围</button><pre id="learningAcceptance"></pre><button id="learningVerify">验收冻结机器切片</button><p>仅核对所选Task的基线、新增及来源修订；不代表语义或正常宿主闭环通过。</p><pre id="learningChecks"></pre>';
let learningAcceptance=null;
learningBox.append(learningChecks);$('learningGuards').onclick=guarded(async()=>{$('learningChecks').textContent=JSON.stringify(await api('learning_register_guards'),null,2)});
$('learningVerifyTask').oninput=()=>{learningAcceptance=null;$('learningAcceptance').textContent='Task已改变，请重新读取冻结范围'};
$('learningAcceptanceRead').onclick=guarded(async()=>{learningAcceptance=null;const t=(await api('get',{object_id:$('learningVerifyTask').value.trim()})).object;if(t.object_type!=='TaskContract'||!Array.isArray(t.payload.learning_acceptance?.source_refs))throw Error('所选Task没有明确冻结的learning_acceptance.source_refs，禁止借用旧900验收范围');learningAcceptance={task_id:t.object_id,task_revision:t.revision,expected:t.payload.learning_acceptance.baseline_count+t.payload.learning_acceptance.new_count};$('learningAcceptance').textContent=JSON.stringify({task:learningAcceptance,contract:t.payload.learning_acceptance},null,2)});
$('learningVerify').onclick=guarded(async()=>{if(!learningAcceptance||learningAcceptance.task_id!==$('learningVerifyTask').value.trim())throw Error('请先读取所选Task的冻结验收范围');$('learningChecks').textContent=JSON.stringify(await api('learning_verify',learningAcceptance),null,2)});
const metadataButton=document.createElement('button');metadataButton.id='learningMetadata';metadataButton.textContent='补回原始AI版本标记';learningChecks.append(metadataButton);metadataButton.onclick=guarded(async()=>{$('learningChecks').textContent=JSON.stringify(await api('learning_metadata'),null,2)});

const reviewButton=document.createElement('button');reviewButton.textContent='保存当前GPT复核与知识警示';reviewButton.id='learningReviewSubmit';$('learningManual').parentElement.after(reviewButton);reviewButton.onclick=guarded(async()=>{$('learningChecks').textContent=JSON.stringify(await api('learning_review',JSON.parse($('learningManual').value)),null,2)});

const fallbackBox=document.createElement('div');fallbackBox.innerHTML='<button id="learningCurrentHost">交回当前工作宿主</button><button id="learningAutoRoute">恢复可用的外部模型路线</button><button id="learningHostInput">读取当前宿主待处理候选</button><pre id="learningHostInputBody"></pre>';learningBox.append(fallbackBox);
$('learningCurrentHost').onclick=guarded(async()=>{await api('learning_route',{route:'current_host'});await learningLoad()});$('learningAutoRoute').onclick=guarded(async()=>{await api('learning_route',{route:'auto'});await learningLoad()});$('learningHostInput').onclick=guarded(async()=>{$('learningHostInputBody').textContent=JSON.stringify(await api('learning_batch_input',{limit:1}),null,2)});

const repairButton=document.createElement('button');repairButton.id='learningReconcile';repairButton.textContent='程序整理已结算例外（不重跑模型）';learningBox.append(repairButton);repairButton.onclick=guarded(async()=>{$('learningChecks').textContent=JSON.stringify(await api('learning_reconcile',{}),null,2);await learningLoad()});
const nativeLabel=document.createElement('label');nativeLabel.textContent='当前对账Task';const nativeTask=document.createElement('input');nativeTask.id='nativeReconcileTask';nativeTask.placeholder='只对账明确映射的当前Task UUID';nativeLabel.append(nativeTask);learningBox.append(nativeLabel);
const nativeInspect=document.createElement('button');nativeInspect.textContent='检查当前Task未知宿主观察';learningBox.append(nativeInspect);const nativeResults=document.createElement('div');learningBox.append(nativeResults);
nativeInspect.onclick=guarded(async()=>{const result=await api('learning_native_operations',{task_id:nativeTask.value.trim()});nativeResults.replaceChildren();for(const row of result.rows){const text=document.createElement('p');text.textContent=`已入库观察 ${row.event_id} · ${row.native_type||'未知类型'} · operation ${row.native_operation} · Task @${row.task_ref.revision}`;const button=document.createElement('button');button.textContent='对账此已入库观察（不重放宿主工作）';button.onclick=guarded(async()=>{const receipt=await api('learning_reconcile',{native_operation:row.native_operation,event_id:row.event_id,task_id:row.task_ref.object_id,task_revision:row.task_ref.revision});$('learningChecks').textContent=JSON.stringify(receipt,null,2);button.disabled=true;await learningLoad()});nativeResults.append(text,button)}if(!result.rows.length)nativeResults.textContent='此范围没有可匹配的未知观察；未匹配项不自动当作已解决。';});

const useButton=document.createElement('button');useButton.id='learningEnableUse';useButton.textContent='启用映射宿主的按需资产调用';learningBox.append(useButton);useButton.onclick=guarded(async()=>{await api('learning_enable_use',{hosts:['dsh','codex'],authorization:'当前用户明确要求：让既有来源的知识和问题边界在正常UACF工作中按需使用，补回DSH调用链。仅向已明确映射的宿主Task提供有界候选，不开放原始档案，不改变原件ACL。'});$('learningChecks').textContent=JSON.stringify(await api('learning_rebuild_use'),null,2)});

const probeButton=document.createElement('button');probeButton.id='learningProbe';probeButton.textContent='回灌旧候选：重复/独立性/审查测试';learningBox.append(probeButton);probeButton.onclick=guarded(async()=>{$('learningChecks').textContent=JSON.stringify(await api('learning_probe',{}),null,2)});

/* Runtime inspector: an existing front-end entry, not a separate one-off report. */
const assetUse=document.createElement('section');assetUse.id='learningAssetUse';
assetUse.innerHTML='<h2>错题与知识怎样用于工作</h2><p>原始实例保留。共同原则可共用入口，条件分支保留。上下文候选、语义审查与执行硬约束分别展示。</p><button id="assetUseRefresh">查看资产使用与审查</button><div id="assetUseSummary"></div><h3>硬约束实际约束哪一步</h3><p>以下约束已注册的执行或交付边界；不检查AI私有思考。hash锁定身份、修订与文件，不能代替理解用户意图。</p><div id="assetUseGuards"></div><h3>来源与模型</h3><div id="assetUseAI"></div><h3>语义重复、条件分支与独立问题</h3><div id="assetUseSemantic"></div><button id="assetSemanticBuild">重建语义待审队列（不调用模型）</button><button id="assetSemanticPending">查看下一对待审病例</button><div id="assetSemanticPair"></div><details><summary>特殊情况手动回填语义审查</summary><p>必须写语义原则、依据和条件差别；相似度不是结论。正常工作宿主可通过既有next/submit工具继续审查。</p><textarea id="assetSemanticInput" aria-label="语义审查回填 JSON"></textarea><button id="assetSemanticSubmit">保存语义审查</button></details><h3>逐条查看原候选及去向</h3><label>候选类型 <select id="assetUseKind"><option value="issues">问题/边界</option><option value="knowledge">知识</option></select></label><label>筛选 <input id="assetUseQuery" placeholder="例如 德语、端口、附件、未检验"></label><button id="assetUseSearch">查询候选去向</button><button id="assetUsePrev">上一页</button><button id="assetUseNext">下一页</button><div id="assetUseRows"></div><pre id="assetUseDetail"></pre>';
learningBox.before(assetUse);const semanticReviewList=document.createElement('div');semanticReviewList.id='assetSemanticReviews';$('assetUseSemantic').after(semanticReviewList);let assetOffset=0,assetPage=null;
function assetTable(target,heads,rows){const table=document.createElement('table');const header=document.createElement('tr');for(const h of heads){const th=document.createElement('th');th.textContent=h;header.append(th)}table.append(header);for(const row of rows){const tr=document.createElement('tr');for(const cell of row){const td=document.createElement('td');if(cell instanceof Node)td.append(cell);else td.textContent=String(cell??'');tr.append(td)}table.append(tr)}$(target).replaceChildren(table)}
const semanticNames={same_principle:'共同原则，保留各自条件',equivalent_conditions:'条件语义等价，可共用模式入口',different_conditions:'相关原则，条件分支不同',independent:'独立问题，不合并',insufficient_evidence:'依据不足，未决'};
async function assetUseLoad(){if(!browserAuthenticated)return;const r=await api('learning_inspect',{query:$('assetUseQuery').value,pair_query:$('assetUseQuery').value,kind:$('assetUseKind').value,offset:assetOffset,limit:12});assetPage=r;
 $('assetUseSummary').textContent=`${r.overview.sources}已索引候选来源：${r.overview.knowledge}知识候选，${r.overview.issues}问题/边界实例。整体语义验收：未完成。${r.overview.automation}。${r.overview.effect}。`;
 assetTable('assetUseGuards',['规则','实际检查与边界','规范规则引用'],r.guards.map(x=>[x.name,x.meaning,`${x.ref.object_id}@${x.ref.revision}`]));
 $('assetUseAI').textContent=`${r.ai.origin||'尚无来源模型说明'}；${r.ai.recorded_sources??0}来源有模型记录，${r.ai.unknown_sources??0}未知。同一来源可能多版本，不能把候选数当模型错误率。`;
 $('assetUseSemantic').textContent=`${r.semantic.proposed_pairs}对检索待审提案；已完成${r.semantic.reviewed_pairs}对语义审查，涉及${r.semantic.reviewed_cases}/${r.semantic.cases}个实例。其余${r.semantic.unreviewed_cases}实例尚无此类审查。${Object.entries(r.semantic.verdict_counts).map(([k,v])=>semanticNames[k]+': '+v).join('；')}。未检索出相邻项不代表独立，也不能把727相关/274扩展候选当成已合并。`;
 assetTable('assetSemanticReviews',['原实例一','原实例二','语义判断与共同原则','条件比较'],r.semantic.rows.map(x=>[x.left.conditions.actual,x.right.conditions.actual,semanticNames[x.review.review.verdict]+'；'+x.review.review.principle,x.review.review.condition_comparison]));
 const data=r.rows.map((x,i)=>{const b=document.createElement('button');b.textContent='查看条件、依据与来源';b.onclick=()=>{$('assetUseDetail').textContent=JSON.stringify(x,null,2)};return [x.title,x.ai_origin?.classifier||'未观察分类回执',x.candidate?.trigger||x.candidate?.text||JSON.stringify(x.candidate),x.semantic_reviews?.map(z=>z.principle).join('；')||'尚无语义关系审查',x.layer,b]});assetTable('assetUseRows',['来源标题','实际分类模型','候选内容','复用原则','进入哪一层','详情'],data);$('assetUsePrev').disabled=assetOffset===0;$('assetUseNext').disabled=assetOffset+r.rows.length>=r.total;
}
$('assetUseRefresh').onclick=guarded(assetUseLoad);$('assetUseSearch').onclick=guarded(async()=>{assetOffset=0;await assetUseLoad()});$('assetUsePrev').onclick=guarded(async()=>{assetOffset=Math.max(0,assetOffset-12);await assetUseLoad()});$('assetUseNext').onclick=guarded(async()=>{assetOffset+=12;await assetUseLoad()});
$('assetSemanticBuild').onclick=guarded(async()=>{await api('learning_semantic_build');await assetUseLoad()});$('assetSemanticSubmit').onclick=guarded(async()=>{const value=JSON.parse($('assetSemanticInput').value);await api('learning_semantic_submit',value);await assetUseLoad()});
$('assetSemanticPending').onclick=guarded(async()=>{const r=await api('learning_semantic_overview',{limit:1,unreviewed_only:true});const x=r.rows[0];$('assetSemanticPair').textContent=x?JSON.stringify(x,null,2):'没有检索待审对；这不代表整体语义审查完成';});

const checkpointBox=document.createElement('details');checkpointBox.innerHTML='<summary>工作中的重要纠错与聚合节点</summary><p>纠错、需求变化、里程碑或用户满意时可引用真实公开事件整理；短日常保留轻量记录。同工作补充聚合，不按情绪或上下文长度制造错题。缺结束事件不能报自动闭环通过；长期未用自动归档尚未接通。</p><label>真实事件检查点 JSON <textarea id=learningCheckpointInput></textarea></label><button id=learningCheckpointSubmit>记录重要工作检查点</button><pre id=learningCheckpointResult></pre>';learningBox.append(checkpointBox);$('learningCheckpointSubmit').onclick=guarded(async()=>{$('learningCheckpointResult').textContent=JSON.stringify(await api('learning_checkpoint',JSON.parse($('learningCheckpointInput').value)),null,2);await learningLoad()});
