/* Permanent bilingual view. Original assets are data, never UI instructions. */
let observeSnapshot=null,observeBusy=false,observeOffset=0,observeTimer=null;
let displayLanguage='zh';try{displayLanguage=localStorage.getItem('uacf.displayLanguage')==='en'?'en':'zh'}catch{}
const vocabulary={
 title:['资产、错题与工作接续','Assets, lessons and continuity'],language:['显示语言','Display language'],search:['查找原始标题','Find original titles'],update:['刷新当前状态','Refresh current state'],previous:['上一页','Previous'],next:['下一页','Next'],assets:['旧库资产','Archived assets'],lessons:['错题与错误证据','Failures and evidence'],work:['当前任务、采纳与使用','Tasks, adoption and recorded use'],history:['对象修订历史','Object revision history'],system:['系统代码更新','System code updates'],explain:['系统怎样工作','How the system works'],advanced:['维护与工程控制（平时可以收起）','Maintenance and engineering controls (optional)'],notAuth:['认证后自动读取；此入口长期保留。不会重新解析原件或调用模型。','Authenticate to read current facts automatically. This permanent view does not reparse sources or call models.'],empty:['当前访问域没有记录；这不表示已经验证无问题。','No records in this access domain; this does not establish absence of problems.'],stored:['原文已保存，尚未理解','Stored; not semantically interpreted'],selected:['已有选中片段，仍待理解','Selected spans; interpretation pending'],unknown:['未知／尚未判断','Unknown / not assessed'],sourceOnly:['仅能定点查阅来源；不是已验证知识或当前授权','Source lookup only; not validated knowledge or current authority'],detail:['展开来源、修订和记录依据','Show source, revision and recorded basis'],original:['原文（保持原语言）','Original text (language unchanged)'],basis:['依据与适用范围','Evidence and applicability'],use:['已记录的直接依赖使用','Recorded direct dependency use'],noUse:['没有直接使用记录；不能据此断言从未使用','No direct recorded use; this does not prove never used'],domains:['领域判断','Domain judgment'],errors:['错误判断','Failure judgment'],languageBasis:['标题字符：','Title scripts: '],langUnknown:['不是已确认的全文语言','Not confirmed full-text language'],provisional:['合成题的临时评审，不能当作旧库真实错误的最终裁决','Provisional synthetic-prompt assessment; not a final diagnosis of a real archived error'],runtime:['实际运行观察；根因与适用性另需核对','Actual runtime observation; root cause and applicability remain separate'],more:['查看规范对象','Inspect canonical object'],noSourceTranslation:['原文尚无核验译文；英文界面不会自动改写它','No verified translation of this source; the English interface does not silently rewrite it'],refreshHint:['每15秒核对新增事件、归档检查点与代码版本；没有变化不重做。','Checks new events, archive checkpoints and code identity every15s; unchanged data is not reprocessed.']};
const tr=k=>vocabulary[k]?.[displayLanguage==='en'?1:0]||k;
function make(tag,text,parent){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(parent)parent.append(n);return n}
function applyDisplayLanguage(){document.documentElement.lang=displayLanguage==='en'?'en':'zh-CN';document.querySelectorAll('[data-i18n]').forEach(n=>n.textContent=tr(n.dataset.i18n));document.querySelectorAll('[data-zh]').forEach(n=>n.textContent=n.dataset[displayLanguage==='en'?'en':'zh']);$('displayLanguage').value=displayLanguage;try{localStorage.setItem('uacf.displayLanguage',displayLanguage)}catch{};if(observeSnapshot)renderObserve();else show('observeState',tr('notAuth'))}
function basisBox(parent,value){const d=make('details',undefined,parent);make('summary',tr('detail'),d);make('pre',JSON.stringify(value,null,2),d)}
function openCanonical(id){const b=make('button',tr('more'));b.onclick=guarded(async()=>{select((await api('get',{object_id:id})).object);$('engineering').open=true;$('detail').scrollIntoView({block:'center'})});return b}
function knownLesson(f){const original=f.lesson||'';const translations={
 '源代码与 package/link 存在不能证明当前进程已加载；核验独立工具调用与 loaded identity 后再接纳。':'Source code and package/link presence do not prove that the running process loaded it. Verify an independent tool call and loaded identity before acceptance.',
 '保留已经限定的整体请求；FULL是局部语义重处理，不强行读全文；明确继续指令不因历史引用再次确认。':'Preserve the request as qualified by the later wording. FULL reprocesses affected semantics and does not force reading all history. An explicit continuation should not be re-confirmed solely because it quotes history. This legacy provisional lesson still needs reconciliation with the current human feedback.',
 '当前DSH原生工具canary被既有Governor wall-clock拦截。HTTP200/ok不等于验证通过；禁止规避Governor或伪造turn/session，待真实宿主边界或支持的维护接口后复核。':'The DSH native tool canary was blocked by the existing Governor wall-clock limit. HTTP200/ok is not a validation pass. Do not bypass Governor or fabricate turn/session identity; recheck at an authorized host boundary or supported maintenance interface.',
 '附件magic/hash与定位成功不能冒充规范Artifact登记成功；保持locator字符串合同，实际登记/blob恢复都要验证；失败IO与成功覆盖分开。':'Successful attachment magic/hash checks and location do not establish successful canonical Artifact registration. Preserve the locator string contract; verify actual registration and blob recovery; separate failed I/O from successful coverage.'};
 return displayLanguage==='zh'?original:(translations[original]||tr('noSourceTranslation'));
}
function renderObserve(){const r=observeSnapshot,c=r.counts;show('observeState',displayLanguage==='zh'?`当前规范库：${c.matching_conversations} 个匹配对话，${c.selected_conversations} 个对话有选中片段；${c.failure_cases} 个错误记录（含临时评审）。水位 ${r.commit_seq}。`:`Canonical state: ${c.matching_conversations} matching conversations; ${c.selected_conversations} conversations with selected spans; ${c.failure_cases} failure records (including provisional assessments). Event ${r.commit_seq}.`);show('observeHint',tr('refreshHint'));
 const a=$('observeAssets');a.replaceChildren();if(!r.assets.length)make('p',tr('empty'),a);
 for(const item of r.assets){const card=make('article',undefined,a);make('h3',item.title||'—',card);make('span',tr(item.processing==='selected_pending'?'selected':'stored'),card).className='badge';make('p',tr('domains')+'：'+tr('unknown')+' · '+tr('errors')+'：'+tr('unknown'),card);make('p',tr('sourceOnly'),card);make('p',tr('languageBasis')+(item.source_language.observed_scripts.join(' + ')||'—')+' · '+tr('langUnknown'),card);
  for(const selected of item.cards){const d=make('details',undefined,card);make('summary',selected.purpose||tr('selected'),d);make('p',displayLanguage==='zh'?selected.summary:'Source-backed candidate only; project affiliations, interpretation and current adoption have not been independently verified.',d);make('p',tr('use')+'：'+(selected.reuse_refs.length?selected.reuse_refs.map(x=>x.type+' @'+x.revision).join(', '):tr('noUse')),d);d.append(openCanonical(selected.card));basisBox(d,selected)}basisBox(card,{plan:item.plan_id,member:item.member,ordinal:item.ordinal,id:item.native_id,raw_hash:item.raw_hash,source_language:item.source_language});
 }
 const f=$('observeFailures');f.replaceChildren();if(!r.failures.length)make('p',tr('empty'),f);
 for(const failure of r.failures){const card=make('article',undefined,f);make('h3',knownLesson(failure),card);make('p',tr(failure.evidence_kind==='synthetic_prompt_provisional'?'provisional':'runtime'),card);make('p',displayLanguage==='zh'?'细错误标签：'+(failure.diagnostic_tags.join(', ')||'未标注，不能自动认定HU类别'):'Detailed diagnostic tags: '+(failure.diagnostic_tags.join(', ')||'not assigned; HU categories are not inferred'),card);if(displayLanguage==='en'){const d=make('details',undefined,card);make('summary',tr('original'),d);make('p',failure.lesson,d)}card.append(openCanonical(failure.id));basisBox(card,failure)}
 const work=$('observeWork');work.replaceChildren();for(const o of r.work_and_use){const d=make('details',undefined,work);const title=o.payload.goal||o.payload.name||(o.type+' · '+o.payload.lifecycle);make('summary',o.type+' @'+o.revision+' · '+title,d);make('p',tr('original')+'：'+title,d);make('p',displayLanguage==='zh'?'以下依赖证明规范库记录了引用，不能单独证明模型已经注意到它或外部动作成功。':'These dependencies establish recorded reference only; they do not independently prove model attention or external success.',d);d.append(openCanonical(o.id));basisBox(d,o)}
 const hist=$('observeHistory');hist.replaceChildren();for(const o of r.history){const d=make('details',undefined,hist);make('summary',o.at+' · '+o.type+' @'+o.revision+' · '+o.status,d);d.append(openCanonical(o.id));basisBox(d,o)}
 const updates=$('observeSystem');updates.replaceChildren();make('p',displayLanguage==='zh'?'当前代码版本 '+r.deployment.identity:'Current code identity '+r.deployment.identity,updates);for(const u of r.system_updates){const d=make('details',undefined,updates);make('summary',(u.applied_at||'—')+' · '+(u.identity||'—').slice(0,12),d);basisBox(d,u)}
 $('observePrevious').disabled=observeOffset===0;$('observeNext').disabled=observeOffset+r.limit>=c.matching_conversations;
}
async function refreshObserve(force=false){if(!browserAuthenticated||observeBusy)return;observeBusy=true;try{const args={offset:observeOffset,limit:20,query:$('observeQuery').value};if(!force&&observeSnapshot)args.after_cursor=observeSnapshot.cursor;const r=await api('observatory',args);if(!r.unchanged){observeSnapshot=r;renderObserve()}}catch(e){show('observeState',e.message)}finally{observeBusy=false}}
$('displayLanguage').onchange=()=>{displayLanguage=$('displayLanguage').value;applyDisplayLanguage()};$('observeRefresh').onclick=()=>refreshObserve(true);$('observeSearch').onclick=()=>{observeOffset=0;refreshObserve(true)};$('observePrevious').onclick=()=>{observeOffset=Math.max(0,observeOffset-20);refreshObserve(true)};$('observeNext').onclick=()=>{observeOffset+=20;refreshObserve(true)};
const baseRefresh=refresh;refresh=async()=>{await baseRefresh();await refreshObserve(true)};
observeTimer=setInterval(()=>{if(!document.hidden)refreshObserve(false)},15000);window.addEventListener('focus',()=>refreshObserve(false));applyDisplayLanguage();
