// Read-only human projection: explicit reviewed principles, never fuzzy merges.
const opinionBox=document.createElement('section');opinionBox.id='humanOpinions';opinionBox.innerHTML='<h2>历史经验给当前工作什么建议</h2><p>先看共用原则，再展开各自条件和实例。已审原则、未审候选与真实执行规则分开。</p><label>查找意见 <input id="opinionQuery" placeholder="语言、端口、附件、交付"></label><button id="opinionRead">读取人可读意见</button><button id="opinionPrev">上一组意见</button><button id="opinionNext">下一组意见</button><p id="opinionCounts"></p><div id="opinionRows"></div><h3>当前任务的独立命令记录</h3><label>Task <input id="commandTask" placeholder="选择当前任务后读取"></label><button id="commandRead">读取全部有效命令</button><p id="commandCounts"></p><div id="commandRows"></div>';
$('workspace').before(opinionBox);let opinionOffset=0;
function opinionText(parent,tag,text){const el=document.createElement(tag);el.textContent=text;parent.append(el);return el}
async function opinionLoad(){const r=await api('learning_opinions',{query:$('opinionQuery').value,offset:opinionOffset,limit:8});const c=r.counts;$('opinionCounts').textContent=`当前索引${c.indexed_sources}来源、${c.knowledge_candidates}知识候选、${c.issue_instances}问题/边界。已审${c.reviewed_pairs}对，涉及${c.reviewed_instances}实例；${c.unreviewed_instances}实例尚无此类审查。形成${r.total_principles}个已审候选原则入口。来源索引不是总提取覆盖。`;$('opinionRows').replaceChildren();
 for(const x of r.rows){const box=document.createElement('article');opinionText(box,'h3',x.principle);opinionText(box,'p',`${x.instance_count}个实例链接一份原则；${x.rule_status}`);const details=document.createElement('details');opinionText(details,'summary','展开条件分支、对比依据和原实例');for(const p of x.comparisons){opinionText(details,'h4',semanticNames[p.verdict]||p.verdict);opinionText(details,'p',p.comparison);opinionText(details,'p','判断依据：'+p.basis)}for(const item of x.instances){opinionText(details,'h4','原实例 '+item.case_ref.object_id.slice(0,8));const cond=item.conditions;opinionText(details,'p',cond.actual||cond.trigger||'原条件见本地来源');const pre=opinionText(details,'pre',JSON.stringify(cond,null,2));const button=opinionText(details,'button','读取此实例的本地来源');button.onclick=guarded(async()=>{if(!item.card_ref)throw Error('该实例未映射来源卡');const rr=await api('learning_opinion_source',{card_ref:item.card_ref,case_ref:item.case_ref});pre.textContent=JSON.stringify(rr,null,2)});}box.append(details);$('opinionRows').append(box)}
 opinionText($('opinionRows'),'p',r.meaning+' '+r.knowledge_scope);$('opinionPrev').disabled=opinionOffset===0;$('opinionNext').disabled=opinionOffset+r.rows.length>=r.matching_principles;}
$('opinionRead').onclick=guarded(async()=>{opinionOffset=0;await opinionLoad()});$('opinionPrev').onclick=guarded(async()=>{opinionOffset=Math.max(0,opinionOffset-8);await opinionLoad()});$('opinionNext').onclick=guarded(async()=>{opinionOffset+=8;await opinionLoad()});
$('commandRead').onclick=guarded(async()=>{const task=$('commandTask').value.trim()||$('workspaceTask').value;if(!task)throw Error('先选当前Task');const r=await api('command_status',{task_id:task});$('commandCounts').textContent=`Task修订${r.revision}，${r.entries.length}条命令，${r.unresolved}条未完成或未决。新补充不能自动删旧要求，语义提炼由当前宿主并保留来源。`;$('commandRows').replaceChildren();for(const e of r.entries){const box=document.createElement('article');opinionText(box,'h4',e.key+' · '+e.state);opinionText(box,'p',e.text);const details=document.createElement('details');opinionText(details,'summary','原话、解释和来源');opinionText(details,'p',e.source_quote);opinionText(details,'p',e.interpretation_basis);opinionText(details,'p',`${e.source_ref.object_id}@${e.source_ref.revision} · ${e.kind}`);box.append(details);$('commandRows').append(box)}});

