"use strict";
const portablePanel=document.createElement('section');portablePanel.id='portableAssets';
portablePanel.innerHTML='<h2>可分享经验与本地来源 / Shareable lessons</h2><p>本机保留真实来源；导出只含通用原则、条件和合成例子。这里的“已复核”是本地候选，仍需你审查具体发布范围。新草稿和旧资产回填共用此入口，不重提取原文。</p><button id="portableRefresh">刷新模块</button><div id="portableRows"></div><pre id="portablePrivateLinks"></pre><details id="portableEditor"><summary>从已有资产制作或修订脱敏模块</summary><label>查找本机来源 <input id="portableSourceQuery" placeholder="例如 必需工作、端口、德语"></label><button id="portableFindSource">查找现有候选</button><div id="portableSourceRows"></div><p id="portableSourceSelected">先选本地来源；来源身份只保留在本机。</p><label>模块名称标识（英文短词，保持后续更新身份）<input id="portableSlug" placeholder="respect-required-work"></label><div id="portableFields"></div><label>本地抽象依据（不导出）<textarea id="portableBasis"></textarea></label><button id="portableSave">保存脱敏草稿</button><button id="portableReset">另建草稿</button></details><h3>这项工作何时整理 / Capture timing</h3><p>只看当前工作节点的少量信号，不另调用模型。人工标注不冒充原生事件；没有真实结束事件时不能称自动归档已完成。长期闲置扫描只检查已明确启用adaptive的本地任务元数据。</p><label>当前任务 <input id="triggerTask" placeholder="从工作区复制当前任务ID"></label><button id="triggerUseCurrent">使用工作区当前任务</button><div id="triggerSignals"></div><label>简短依据（最多1024 UTF-8字节）<textarea id="triggerCue"></textarea></label><button id="triggerCheck">检查本节点是否需整理</button><button id="triggerStatus">查看触发策略与最近检查</button><p id="portableFeedback" role="status"></p><pre id="triggerResult"></pre>';
$('learningAssetUse').after(portablePanel);
const portableImportPanel=document.createElement('details');
portableImportPanel.innerHTML='<summary>导入可分享经验 / Import advisory lessons</summary><p>选择公开JSON模块。先保存为本地草稿并检查适用条件，复核后才可进入任务上下文；不会安装可执行规则，也不会补造私人历史来源。</p><input type="file" id="portableImportFile" accept="application/json,.json"><label>来源及许可依据（仅保存在本机）<textarea id="portableImportLicense"></textarea></label><button id="portableImport">导入为待审草稿</button>';
$('portableRows').before(portableImportPanel);
const portablePasteLabel=document.createElement('label');portablePasteLabel.textContent='也可粘贴公开JSON（最多256KB） / Paste public JSON';const portablePaste=document.createElement('textarea');portablePaste.id='portableImportText';portablePasteLabel.append(portablePaste);$('portableImportFile').after(portablePasteLabel);
async function portableShowLinks(ref){const links=await api('portable_links',{module_ref:ref});$('portablePrivateLinks').textContent=JSON.stringify(links,null,2);let controls=$('portableSourceControls');if(!controls){controls=document.createElement('div');controls.id='portableSourceControls';$('portablePrivateLinks').before(controls)}controls.replaceChildren();for(const sourceRef of links.source_refs)controls.append(portableButton('读取这个来源的原条件（仅本机）',async()=>{$('portablePrivateLinks').textContent=JSON.stringify(await api('portable_source_detail',{module_ref:ref,source_ref:sourceRef}),null,2)}))}
const portableNames={title:'模块标题 / Title',principle:'通用原则 / Principle',applicable:'适用条件 / Applies when',excluded:'排除条件 / Does not apply when',positive_example:'合成正例 / Synthetic positive example',negative_example:'合成反例 / Synthetic negative example',limitations:'限制与未决 / Limitations'};
for(const [key,name] of Object.entries(portableNames)){const field=document.createElement('fieldset');const legend=document.createElement('legend');legend.textContent=name;field.append(legend);for(const lang of ['zh','en']){const label=document.createElement('label');label.textContent=lang==='zh'?'中文':'English';const input=document.createElement('textarea');input.id='portable_'+key+'_'+lang;input.maxLength=1200;label.append(input);field.append(label)}$('portableFields').append(field)}
const signalLabels={explicit_request:'明确要求整理',correction:'确认纠正',requirement_change:'实质需求变化',progress:'工作进展',owner_satisfied:'明确满意',completion:'明确工作结束',dissatisfaction:'表达不满意（单独不证明错误）',short_daily:'短小日常工作'};
for(const [key,name] of Object.entries(signalLabels)){const label=document.createElement('label');const input=document.createElement('input');input.type='checkbox';input.id='trigger_'+key;label.append(input,document.createTextNode(name));$('triggerSignals').append(label)}
let portableSourceRefs=[],portableEditing=null;
function portableButton(name,run){const b=document.createElement('button');b.textContent=name;b.onclick=guarded(run);return b}
function portableReset(){portableEditing=null;portableSourceRefs=[];$('portableSourceSelected').textContent='先选本地来源；来源身份只保留在本机。';$('portableSlug').value='';$('portableBasis').value='';for(const key of Object.keys(portableNames))for(const lang of ['zh','en'])$('portable_'+key+'_'+lang).value=''}
async function portableLoad(){const r=await api('portable_overview');$('portableRows').replaceChildren();for(const x of r.rows){const article=document.createElement('article');const heading=document.createElement('h3');heading.textContent=x.card.title.zh+' / '+x.card.title.en;article.append(heading);for(const key of ['principle','applicable','excluded','limitations']){const p=document.createElement('p');p.textContent=portableNames[key]+': '+x.card[key].zh+' / '+x.card[key].en;article.append(p)}const status=document.createElement('p');status.textContent='状态：'+x.disclosure+'；'+x.private_link_count+'个本地来源；不推断AI实际使用';article.append(status);
 article.append(portableButton('查看本地来源（不导出）',async()=>portableShowLinks(x.module_ref)),portableButton('编辑并重新复核',async()=>{portableEditing=x.module_ref;const links=await api('portable_links',{module_ref:x.module_ref});portableSourceRefs=links.source_refs;$('portableSlug').value=x.card.slug;for(const key of Object.keys(portableNames))for(const lang of ['zh','en'])$('portable_'+key+'_'+lang).value=x.card[key][lang];$('portableBasis').value=links.basis;$('portableEditor').open=true;$('portableSourceSelected').textContent='修订现有模块；来源保留。修订后旧复核失效。'}));
 if(x.disclosure==='draft')article.append(portableButton('复核此版脱敏内容',async()=>{await api('portable_review',{module_ref:x.module_ref,public_content_hash:x.public_content_hash,basis:'当前授权操作者在本地前台复核具体双语投影：抽象条件和合成例子；不包含原文、私人身份或本机链接。此记录不证明人类最终发布审批，发布范围仍待另行确认。'});await portableLoad()}));
 else article.append(portableButton('下载此版公开候选（不上传）',async()=>{const result=await api('portable_export',{module_refs:[x.module_ref]});const blob=new Blob([JSON.stringify(result.bundle,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=x.card.slug+'.json';a.click();URL.revokeObjectURL(url);$('portableFeedback').textContent='已导出本地候选；hash '+result.sha256+'。没有上传授权；请检查许可和潜在隐私。'}));$('portableRows').append(article)}if(!r.rows.length)$('portableRows').textContent='目前0个脱敏模块。已有私人候选不会自动公开。'}
$('portableRefresh').onclick=guarded(portableLoad);$('portableReset').onclick=portableReset;
$('portableImport').onclick=guarded(async()=>{const file=$('portableImportFile').files[0];const text=file?await file.text():$('portableImportText').value;if(!text||new TextEncoder().encode(text).length>262144)throw new Error('请选择或粘贴不超过256KB的公开JSON模块');const bundle=JSON.parse(text);const result=await api('portable_import',{bundle,license_basis:$('portableImportLicense').value});await portableLoad();$('portableFeedback').textContent='导入结果已回读：'+result.rows.length+'个模块；新模块为待审草稿，没有自动采用规则。'});
$('portableFindSource').onclick=guarded(async()=>{const result=await api('learning_inspect',{kind:'issues',query:$('portableSourceQuery').value,limit:8});$('portableSourceRows').replaceChildren();for(const row of result.rows){const ref=row.case_ref||row.card_ref;const b=portableButton('选择来源：'+row.title,async()=>{portableSourceRefs=[ref];$('portableSourceSelected').textContent='已选本地来源：'+row.title+'。请独立写抽象原则与合成例子，不复制私人原文。'});$('portableSourceRows').append(b)}if(!result.rows.length)$('portableSourceRows').textContent='没有相关候选，保留未决，不编造来源。'});
$('portableSave').onclick=guarded(async()=>{const card={slug:$('portableSlug').value,kind:'principle',topics:['work-guidance'],confidence:'provisional'};for(const key of Object.keys(portableNames))card[key]={zh:$('portable_'+key+'_zh').value,en:$('portable_'+key+'_en').value};const args={card,source_refs:portableSourceRefs,derivation_basis:$('portableBasis').value};if(portableEditing)args.module_ref=portableEditing;await api(portableEditing?'portable_revise':'portable_draft',args);portableReset();await portableLoad();$('portableFeedback').textContent='草稿已回读。原来源未重提取；复核前禁止导出。'});
$('triggerUseCurrent').onclick=()=>{$('triggerTask').value=$('workspaceTask').value||$('task').value};
$('triggerCheck').onclick=guarded(async()=>{const task=(await api('get',{object_id:$('triggerTask').value})).object;const features={cue:$('triggerCue').value};for(const key of Object.keys(signalLabels))features[key]=$('trigger_'+key).checked;$('triggerResult').textContent=JSON.stringify(await api('archive_trigger_check',{task_id:task.object_id,task_revision:task.revision,features}),null,2)});
$('triggerStatus').onclick=guarded(async()=>{$('triggerResult').textContent=JSON.stringify(await api('archive_trigger_status',{task_id:$('triggerTask').value}),null,2)});
