/* Same authority: project controls, source drawer and failure obligations. */
let workspaceSnapshot=null,workspaceSelected='',workspaceBusy=false;
const wt=(zh,en)=>displayLanguage==='en'?en:zh;
function updateWorkspaceLabels(){document.querySelectorAll('[data-wzh]').forEach(n=>n.textContent=n.dataset[displayLanguage==='en'?'wen':'wzh']);if(workspaceSnapshot)renderWorkspace();}
const originalLanguageUpdate=applyDisplayLanguage;applyDisplayLanguage=()=>{originalLanguageUpdate();updateWorkspaceLabels()};
async function loadWorkspace(taskId=''){if(!browserAuthenticated||workspaceBusy)return;workspaceBusy=true;try{const r=await api('workspace',taskId?{task_id:taskId}:{});workspaceSnapshot=r;workspaceSelected=taskId;renderWorkspace()}catch(e){show('workspaceState',e.message)}finally{workspaceBusy=false}}
function svgNode(svg,x,y,label,detail,id){const ns='http://www.w3.org/2000/svg',g=document.createElementNS(ns,'g'),rect=document.createElementNS(ns,'rect'),t=document.createElementNS(ns,'text');Object.entries({x,y,width:180,height:64,rx:9,fill:'#e3f0f3',stroke:'#5f8b9a'}).forEach(([k,v])=>rect.setAttribute(k,v));t.setAttribute('x',x+10);t.setAttribute('y',y+25);t.textContent=label;const d=document.createElementNS(ns,'text');d.setAttribute('x',x+10);d.setAttribute('y',y+46);d.textContent=detail;g.append(rect,t,d);if(id)g.onclick=guarded(async()=>{select((await api('get',{object_id:id})).object);$('engineering').open=true;$('detail').scrollIntoView({block:'center'})});svg.append(g)}
function svgLine(svg,a,b){const n=document.createElementNS('http://www.w3.org/2000/svg','line');Object.entries({x1:a[0],y1:a[1],x2:b[0],y2:b[1],stroke:'#507b8c','stroke-width':2}).forEach(([k,v])=>n.setAttribute(k,v));svg.append(n)}
function newDiagram(parent){const s=document.createElementNS('http://www.w3.org/2000/svg','svg');s.setAttribute('viewBox','0 0 1020 270');s.setAttribute('role','img');s.style.height='270px';parent.append(s);return s}
function renderWorkspace(){const r=workspaceSnapshot,task=r.selected_task;const selectBox=$('workspaceTask');selectBox.replaceChildren(new Option(wt('选择当前任务','Select a task'),''),...r.tasks.sort((a,b)=>b.revision-a.revision).map(t=>new Option(t.goal.slice(0,95)+' @'+t.revision,t.id)));selectBox.value=workspaceSelected;
 show('workspaceState',wt('项目、任务和档案使用同一规范库；图只连接真实记录，未确认的领域不会自动画上去。','Projects, tasks and archives share the same canonical store. Graphs show recorded relationships; unconfirmed domains are not invented.'));
 const workflow=$('workspaceWorkflow'),affiliation=$('workspaceAffiliation'),drawer=$('workspaceSources'),failure=$('workspaceLessons');for(const box of [workflow,affiliation,drawer,failure])box.replaceChildren();
 const memberships=new Map();for(const a of r.affiliations){if(a.payload.lifecycle!=='confirmed')continue;const id=a.payload.asset_id;if(!memberships.has(id))memberships.set(id,[]);memberships.get(id).push(a)}
 if(!memberships.size)make('p',wt('尚未登记语义归属。客户端标题或移动项目不会在这里自动变成归属。','No semantic membership registered. Client titles and project moves do not create it.'),affiliation);
 for(const [id,entries] of memberships){const d=make('details',undefined,affiliation);d.open=true;make('summary',(r.affiliation_labels[id]||wt('同一资料片段','One source span')).slice(0,75)+' · '+id.slice(0,8)+' · '+entries.length+wt('个项目引用',' project references'),d);const list=make('ul',undefined,d);for(const a of entries){const project=r.projects.find(p=>p.object_id===a.payload.target_id),li=make('li',undefined,list);make('span',project?.payload.name||a.payload.target_id,li);li.append(openCanonical(a.object_id));make('p',wt('归属依据：','Membership basis: ')+a.payload.basis,li)}d.append(openCanonical(id))}
 make('p',wt('目录中的多处出现都是引用。项目问题、执行错误和正常拒绝是另外的分类轴；客户端项目组织单列。','Multiple placements are references. Project problems, execution errors and normal refusals are separate facets; native client organisation stays separate.'),affiliation);
 if(!task){make('p',wt('选择任务后展开执行图、来源和适用错题。','Select a task to inspect workflow, sources and applicable lessons.'),workflow);return}
 const graph=newDiagram(workflow);graph.classList.add('workflow-svg');graph.setAttribute('viewBox','0 0 1020 430');graph.setAttribute('aria-label',wt('带准备条件、返回值和纠正回路的工程流程','Engineering flow with preparation gates, returns and correction loops'));
 const ns='http://www.w3.org/2000/svg';const defs=document.createElementNS(ns,'defs'),marker=document.createElementNS(ns,'marker');Object.entries({id:'workflowArrow',viewBox:'0 0 10 10',refX:9,refY:5,markerWidth:7,markerHeight:7,orient:'auto-start-reverse'}).forEach(([k,v])=>marker.setAttribute(k,v));const tip=document.createElementNS(ns,'path');tip.setAttribute('d','M0 0L10 5L0 10Z');tip.setAttribute('fill','#507b8c');marker.append(tip);defs.append(marker);graph.append(defs);
 const line=(path,label,x,y,dashed=false)=>{const p=document.createElementNS(ns,'path');Object.entries({d:path,fill:'none',stroke:'#507b8c','stroke-width':2,'marker-end':'url(#workflowArrow)'}).forEach(([k,v])=>p.setAttribute(k,v));if(dashed)p.setAttribute('stroke-dasharray','5 4');graph.append(p);if(label){const t=document.createElementNS(ns,'text');t.setAttribute('x',x);t.setAttribute('y',y);t.textContent=label;graph.append(t)}};
 const blocked=task.payload.execution_state==='stopped'||task.payload.allow_provider===false||r.context.status!=='ready';
 svgNode(graph,20,35,wt('当前任务','Current task'),'@'+task.revision+' · '+task.status,task.object_id);
 svgNode(graph,270,35,wt('准备输入与约束','Prepare inputs / constraints'),r.context.status,task.object_id);
 const diamond=document.createElementNS(ns,'polygon');diamond.setAttribute('points','580,23 655,67 580,111 505,67');diamond.setAttribute('fill',blocked?'#fff1de':'#e3f0f3');diamond.setAttribute('stroke','#7a8f95');graph.append(diamond);const dt=document.createElementNS(ns,'text');dt.setAttribute('x',541);dt.setAttribute('y',71);dt.textContent=wt('允许执行？','May run?');graph.append(dt);
 svgNode(graph,780,35,wt('宿主执行','Host execution'),wt('按当前合同派发','Under current contract'));
 svgNode(graph,500,165,wt('停在准备阶段','Wait at preparation'),task.payload.execution_state==='stopped'?wt('当前：已停止新增执行','Current: further execution stopped'):r.context.status);
 svgNode(graph,780,205,wt('返回值与执行回执','Returns and receipts'),r.results.length+wt('份已记录回执',' recorded receipts'),r.results[0]?.object_id);
 svgNode(graph,500,315,wt('独立检查','Independent check'),wt('按性质判定，不看HTTP成功','Judge properties, not HTTP success'));
 svgNode(graph,80,315,wt('补证或修订','Evidence / revision'),wt('失败与未决反馈给任务','Feed failure / gaps back to task'),task.object_id);
 line('M200 67H270',wt('输入','inputs'),213,55);line('M450 67H505',wt('准备结果','prepared'),443,22);line('M655 67H780',wt('是：且授权有效','yes + authorised'),657,52,true);line('M580 111V165',wt('否 / 超限 / 已停止','no / overflow / stopped'),594,145);line('M870 99V205',wt('工具/模型返回','tool/model return'),878,155,true);line('M780 237H740V347H680',wt('检查实际返回','check actual return'),726,285);line('M500 347H260',wt('失败 / 证据不全','failure / incomplete evidence'),295,333);line('M170 315V245H110V99',wt('修订后重新准备','revise then prepare'),25,225,true);
 make('p',wt('这是工作流程的条件与反馈关系。虚线是有条件的后续动作，不表示已执行；当前任务已经停止时不会继续派发。下面单列真实历史调用，不把旧回执算到当前修订。','This diagram shows gates and feedback. Dashed edges are conditional, not proof of execution. Actual historical calls follow below and do not validate the current revision.'),workflow).className='workflow-note';
 if(r.execution_trace?.length){make('h3',wt('真实调用与返回','Recorded calls and returns'),workflow);const rounds=new Map();for(const row of r.execution_trace){let box=rounds.get(row.turn);if(!box){box=make('div',undefined,workflow);box.className='native-round';make('h4',wt('第','Turn ')+row.turn+wt('轮 · 执行时Task @',' · executed Task @')+row.task_revision,box);rounds.set(row.turn,box);if(row.turn===2)make('p',wt('接续纠正：DOM检查不能代替浏览器/Excel验收，再次复核undo。','Follow-up correction: DOM checks do not validate browser/Excel behaviour; verify undo again.'),box)}const step=make('div',undefined,box);step.className='native-step';make('span',row.tool+'('+row.arguments.scenario+')',step);make('span','→',step).className='native-arrow';make('span',wt('返回 #','Return #')+row.return_seq+' · '+(row.is_error===false?wt('非错误','not error'):wt('未知/错误','unknown/error')),step);make('span','→',step).className='native-arrow';make('span',row.independent_stdout_match?wt('独立stdout一致','Independent stdout matches'):wt('独立检查未知','Independent check unknown'),step);basisBox(box,row);const original=make('details',undefined,box);make('summary',wt('展开这次工具返回','Open this tool return'),original);let loaded=false;original.addEventListener('toggle',async()=>{if(!original.open||loaded)return;loaded=true;try{const output=await api('catalog',{mode:'native-return',key:row.evidence_id,seq:row.return_seq});make('pre',output.record.result.stdout,original)}catch(e){loaded=false;make('p',e.message,original)}})}}else make('p',wt('尚无可展开的真实工具调用链；已有Evidence仍可在来源中查。不会按阶段名称编造执行步骤。','No expandable native tool trace is available; inspect existing Evidence separately. Stage names do not create an execution trace.'),workflow);
 show('workspaceCapsule',wt('当前上下文状态：','Current context status: ')+r.context.status+' · '+r.context.required_bytes+' bytes');
 for(const entry of r.source_closure){const o=entry.object,d=make('details',undefined,drawer);make('summary',o.object_type+' @'+o.revision+' · '+(entry.stale?wt('旧依赖或已失效','old/stale dependency'):wt('确切引用','exact reference')),d);if(o.object_type==='Message'||o.object_type==='SemanticCard')make('p',o.payload.summary||(o.payload.text===undefined?wt('点击记录后再读取原文。','Open the record to read source.'):JSON.stringify(o.payload.text).slice(0,900)),d);d.append(openCanonical(o.object_id));basisBox(d,{id:o.object_id,revision:o.revision,current_revision:entry.current_revision,locator:o.payload.locator,input_vector:o.payload.input_vector})}
 if(!r.source_closure.length)make('p',wt('没有已记录的来源依赖；不能自动推定已经参考旧库。','No recorded source dependencies; use of the archive is not presumed.'),drawer);
 const assessed=r.failure_assessment;make('p',wt('适用义务：','Applicable obligations: ')+assessed.effective_obligations.length+' · '+wt('已排除：','Excluded: ')+assessed.excluded.length,failure);
 for(const item of assessed.effective_obligations){const d=make('details',undefined,failure);make('summary',wt('当前适用','Applicable now')+' · '+item.lesson,d);basisBox(d,item)}
 for(const item of assessed.excluded){const d=make('details',undefined,failure);make('summary',wt('未采用','Not applied')+' · '+item.reasons.join('; '),d);basisBox(d,item)}
 if(!assessed.candidates.length)make('p',wt('没有匹配所需性质的已记录候选。此处为空不证明旧项目没有出错。','No recorded candidates match required properties. An empty list does not prove previous projects had no errors.'),failure);
 const roles=$('workspaceRoute');roles.replaceChildren();make('p',wt('当前可执行E7路由在页面顶部配置；这里保留任务的历史关系与依据。其他任务没有登记执行模板时不会自动派发。','Configure the executable E7 route at the top. This view retains historical task relationships. Tasks without an execution template are not dispatched.'),roles);
}
$('workspaceTask').onchange=()=>loadWorkspace($('workspaceTask').value);$('workspaceRefresh').onclick=()=>loadWorkspace(workspaceSelected);
const refreshWithObserve=refresh;refresh=async()=>{await refreshWithObserve();await loadWorkspace(workspaceSelected)};
setInterval(()=>{if(browserAuthenticated&&!document.hidden&&workspaceSnapshot&&observeSnapshot&&workspaceSnapshot.commit_seq!==observeSnapshot.commit_seq)loadWorkspace(workspaceSelected)},16000);updateWorkspaceLabels();
