/* Applied route + actual worker. Graph nodes are controls, history is separate. */
let flowState=null,flowLoading=false,flowGeneration=0;
async function flowLoad(){if(!browserAuthenticated||flowLoading)return;flowLoading=true;const generation=flowGeneration;try{const result=await api('workflow_status');if(generation===flowGeneration){flowState=result;flowRender()}}catch(e){$('flowStatus').textContent=e.message}finally{flowLoading=false}}
function flowRender(){$('flowBatchCurrent')&&($('flowBatchCurrent').textContent='当前批次：'+flowState.batch_directory);const r=flowState,s=r.status,c=r.config,sel=r.selection;const active=r.worker_alive,waiting=s.state==='waiting_host_review'; const names={ready:'待配置',queued:'已排队',running:'执行中',idle:'阶段完成',waiting_host_review:'等待Codex宿主审核',paused:'已暂停',blocked:'已停止，请核对回执',published:'候选已入库'};$('flowStatus').textContent=`${names[s.state]||s.state} · ${s.stage||''}${s.title?' · 最近活动：'+s.title:''}${s.current_part?' · 片段'+s.current_part+'/'+s.total_parts:''}`;$('flowError').textContent=s.error||'没有未解决的原始错误';$('flowSourceList').replaceChildren();for(const row of sel.packets||[]){const line=document.createElement('p');line.textContent='#'+row.index+' · '+row.title+' · '+row.chars.toLocaleString()+' 字符';$('flowSourceList').append(line)};$('flowManifest').textContent=JSON.stringify({source_manifest:sel.selection,selected_public_chars:sel.selected_chars,packets:sel.packets},null,2);$('flowProgress').textContent=`已提取 ${s.completed?.length||0} / ${sel.packets?.length||0} · GPT复核 ${s.reviewed?.length||0} · 选定正文 ${(sel.selected_chars||0).toLocaleString()} 字符`;
 $('flowApplied').textContent=c.revision?`已应用 @${c.revision}：提取 ${c.extract} / ${c.host}；GPT审核目标 ${c.review_percent}% 正文；固定错题快照；并行提取 ${c.concurrency||1}。`:'尚未应用配置。选择预设或节点，保存后才会执行。';
 $('flowRepair').hidden=s.error!=='INVALID_JSON_REQUIRES_EXPLICIT_CORRECTION';$('flowRepair').disabled=active;$('flowResolve').hidden=!(s.state==='blocked'&&String(s.error).includes('model is not supported'));
 $('hostReview').hidden=s.state!=='waiting_host_review';if(s.state==='waiting_host_review')$('hostReviewStatus').textContent=`请求 ${r.host_request.request_id} · 来源 #${r.host_request.index} · ${r.host_request.public_chars.toLocaleString()}字符 · 片段 ${(r.host_request.part||0)+1}/${r.host_request.part_count||1} · 当前桌面Codex 6.1 SOL / medium。等待实际宿主回填；尚未完成审核。`;
 for(const id of ['flowApply','flowProbe','flowPilot','flowReview','flowProduction','flowPublish'])$(id).disabled=active||waiting||!sel.packets?.length;
 $('flowPause').disabled=!active&&!waiting;$('flowPublish').disabled=active||waiting||(s.completed?.length!==sel.packets?.length);$('flowProduction').textContent='继续完成'+(sel.packets?.length||0)+'来源';
 $('flowNodeExtract').textContent='② 完整来源提取\n'+(c.extract||'选择模型');$('flowNodeReview').textContent='④ 语义复核\nGPT · '+(c.review_percent??30)+'%正文';
 const events=$('flowEvents');events.replaceChildren();for(const e of (s.events||[]).slice().reverse()){const line=document.createElement('p');line.textContent=`${e.action} · 实际GPT正文 ${Math.round(e.gpt_text_share*100)}% · ${(e.source_chars||0).toLocaleString()}字符 · ${e.config.host} · ${e.at}`;events.append(line)}
 if(!events.children.length)events.textContent='执行后显示实际比例、时间与回执。比例按正文衡量，Token另计；旧回执不会充当当前修订成功。';
}
function flowPreset(name){$('flowStageControls').hidden=false;const presets={cost:[5,'deepseek-flash','codex_deepseek'],time:[10,'deepseek-flash','codex_deepseek'],quality:[100,'deepseek-flash','codex_deepseek']},p=presets[name];$('flowRatio').value=p[0];$('flowExtract').value=p[1];$('flowHost').value=p[2];$('flowPreset').value=name;$('flowConcurrency').value=name==='cost'?1:3;document.querySelectorAll('[data-flow-preset]').forEach(x=>x.classList.toggle('active',x.dataset.flowPreset===name));$('flowInspector').hidden=false;$('flowDraft').textContent='待应用草稿；初始预设需本轮校准，未宣称普遍最优。'}
document.querySelectorAll('[data-flow-preset]').forEach(x=>x.onclick=()=>flowPreset(x.dataset.flowPreset));
document.querySelectorAll('[data-flow-node]').forEach(x=>x.onclick=()=>{$('flowInspector').hidden=false;$('flowStageControls').hidden=!['extract','review'].includes(x.dataset.flowNode);$('flowSourceManifest').hidden=x.dataset.flowNode!=='source';if(x.dataset.flowNode==='source')$('flowSourceManifest').open=true;$('flowInspectorTitle').textContent=x.dataset.flowNode==='extract'?'完整来源提取：选择模型与宿主':x.dataset.flowNode==='review'?'语义复核：调整GPT完整阅读比例':'固定安全阶段：程序执行，无模型替代';$('flowDraft').textContent=x.dataset.flowNode==='review'?'增加比例后可补审实验样本；已存在回执复用，避免重做。':'节点配置保存为规范路由修订，再启动执行。'});
$('flowApply').onclick=guarded(async()=>{const r=await api('workflow_configure',{extract:$('flowExtract').value,host:$('flowHost').value,review_percent:Number($('flowRatio').value),preset:$('flowPreset').value,concurrency:Number($('flowConcurrency').value),review_policy:$('flowReviewPolicy').value,expected_revision:flowState.config.revision||0});flowGeneration++;flowState.config=r.config;flowRender();$('flowDraft').textContent='配置已保存；规范引用 '+r.config.canonical_ref.object_id;$('flowInspector').hidden=true;await flowLoad()});
async function flowStart(scope){const result=await api('workflow_start',{scope,expected_revision:flowState.config.revision||0});flowGeneration++;flowState.status={...flowState.status,state:'queued',stage:'前台启动已留痕',active_scope:scope,run_ref:result.run_ref};flowState.worker_alive=true;flowRender();await flowLoad()}
for(const [id,scope] of [['flowProbe','probe'],['flowPilot','pilot'],['flowReview','review'],['flowProduction','production'],['flowPublish','publish']])$(id).onclick=guarded(()=>flowStart(scope));
$('flowRepair').onclick=guarded(()=>flowStart('repair'));
$('flowPause').onclick=guarded(async()=>{await api('workflow_pause');await flowLoad()});$('flowRefresh').onclick=flowLoad;
$('flowResolve').onclick=guarded(async()=>{await api('workflow_resolve_rejection');await flowLoad()});
$('hostReadSource').onclick=guarded(async()=>{const r=await api('workflow_review_request');$('hostSource').textContent=JSON.stringify(r,null,2);$('hostSource').parentElement.open=true});
$('hostSubmit').onclick=guarded(async()=>{const scope=flowState.status.active_scope||'review';await api('workflow_review_submit',{request_id:flowState.host_request.request_id,result:JSON.parse($('hostResult').value)});$('hostResult').value='';$('hostSource').textContent='';await flowLoad();await flowStart(scope)});
const flowOriginalRefresh=refresh;refresh=async()=>{await flowOriginalRefresh();await flowLoad()};
setInterval(()=>{if(browserAuthenticated&&!document.hidden)flowLoad()},4000);flowPreset('time');$('flowInspector').hidden=true;flowLoad();

/* General stage ledger: the existing host continues; no duplicate GPT inference. */
const projectBox=document.createElement('section');projectBox.id='projectExecution';
projectBox.innerHTML=`<h2>当前项目的阶段与默认分工</h2><p>当前GPT直接继续本聊天工作，控制台记录和约束路由，无需再次调用GPT。人工修改可选。外部模型仍使用已注册的执行器；默认步骤全部由当前宿主处理，不依赖安装DSH或DeepSeek；外部步骤需显式选择注册执行器。</p><label>规范任务 <input id="projectTask" placeholder="当前Task UUID"></label><button id="projectLoad">读取项目阶段</button><label>任务类型 <select id="projectFamily"><option value="general">一般工程</option><option value="assets">资产整理</option><option value="code">代码工程</option><option value="report">报告研究</option></select></label><label>默认侧重 <select id="projectPreset"><option value="time">时间：当前宿主处理，可选外部协助</option><option value="cost">费用：复用已有结果，外部调用可选</option><option value="quality">质量：当前宿主复核，程序核验</option></select></label><button id="projectDefault">生成默认步骤</button><button id="projectAdd">增加步骤</button><div id="projectStages" style="display:flex;gap:12px;flex-wrap:wrap;align-items:stretch;margin:16px 0"></div><button id="projectSave">保存项目步骤与路由</button><p id="projectStatus" role="status"></p><details><summary>AI拟定步骤或高级修订（可选）</summary><label>步骤 JSON <textarea id="projectJSON"></textarea></label><button id="projectImport">采用拟定步骤</button></details><div id="projectReceipt" hidden><h3 id="projectStepTitle"></h3><button id="projectBegin">记录阶段开始并由当前宿主继续</button><label>公开结果与边界 <textarea id="projectResult"></textarea></label><label>原生回执或文件定位 <input id="projectLocator"></label><button id="projectFinish">记录阶段结果</button></div><p class="muted">记录开始不等于另开推理；记录结果是宿主报告，不等于独立验收。反馈和新增工作保存为新方案修订，旧方案与回执保留。任意拖拽循环编辑器仍未提供。</p>`;
$('observatory').before(projectBox);
let projectData=null,projectDraft=[],projectStep=null;
function projectRender(){const graph=$('projectStages');graph.replaceChildren();for(const s of projectDraft){const box=document.createElement('div');box.style.cssText='min-width:240px;flex:1 1 260px;border:1px solid #8aa7af;border-radius:8px;padding:12px;background:#edf5f6';const button=document.createElement('button');button.textContent=s.label;button.onclick=()=>{projectStep=s;$('projectReceipt').hidden=false;$('projectStepTitle').textContent=s.label+' · '+s.route;};const label=document.createElement('label');label.textContent='执行者';const route=document.createElement('select');route.setAttribute('aria-label',s.label+'执行者');route.add(new Option('当前GPT直接继续','current_host'));route.add(new Option('DeepSeek（需注册执行器）','deepseek'));route.value=s.route;route.onchange=()=>{s.route=route.value;$('projectStatus').textContent='未保存的路由修改';};label.append(route);const state=document.createElement('p');const events=projectData?.plan?.events||[];state.textContent=events.some(e=>e.stage_id===s.id&&e.state==='completed')?'结果已记录':events.some(e=>e.stage_id===s.id&&e.state==='started')?'宿主执行中':'待执行';box.append(button,label,state);graph.append(box)}$('projectJSON').value=JSON.stringify(projectDraft,null,2)}
async function projectLoad(){projectData=await api('workflow_project_status',{task_id:$('projectTask').value.trim()});projectDraft=structuredClone(projectData.plan?.config.stages||projectData.defaults);projectRender();$('projectStatus').textContent='合同必需工序 '+projectData.required_work_steps.length+'：'+projectData.required_work_steps.join(' → ')+'。阶段预览/宿主报告不代表这些工序已验收。 '+(projectData.plan?'方案已保存 · Task @'+projectData.task_ref.revision+' · 当前宿主直接继续':'默认步骤待保存 · 当前宿主无需再次调用GPT')}
$('projectLoad').onclick=guarded(projectLoad);
$('projectDefault').onclick=()=>{const rows=[['plan','理解目标与约束'],['extract','读取来源与结构化'],...($('projectFamily').value==='assets'?[]:[['implement','实施与修订']]),['validate','程序与来源核验'],['review','条件、矛盾与结果复核'],['deliver','交付与接续']];projectDraft=rows.map(([role,label],i)=>({id:'s'+(i+1),role,label,route:'current_host',depends_on:i?['s'+i]:[]}));projectRender();$('projectStatus').textContent='默认分工已拟定；保存后生效，人工修改可选';};
$('projectAdd').onclick=()=>{const id='s'+crypto.randomUUID().slice(0,8);projectDraft.push({id,role:'implement',label:'新增工作步骤',route:'current_host',depends_on:projectDraft.length?[projectDraft.at(-1).id]:[]});projectRender();$('projectStatus').textContent='新增步骤待保存，可在高级修订中调整名称和依赖'};
$('projectImport').onclick=guarded(async()=>{const v=JSON.parse($('projectJSON').value);if(!Array.isArray(v))throw Error('步骤必须是数组');projectDraft=v;projectRender();$('projectStatus').textContent='拟定步骤待保存，服务端会校验依赖与路由'});
$('projectSave').onclick=guarded(async()=>{const draft=structuredClone(projectDraft);if(!projectData||projectData.task_ref.object_id!==$('projectTask').value.trim())await projectLoad();if(draft.length)projectDraft=draft;const r=await api('workflow_project_configure',{task_id:$('projectTask').value.trim(),task_revision:projectData.task_ref.revision,family:$('projectFamily').value,preset:$('projectPreset').value,stages:projectDraft});projectData.plan=r.plan;projectData.task_ref=r.task_ref;projectRender();$('projectStatus').textContent='已保存 · Task @'+r.task_ref.revision+' · 默认当前宿主继续，外部步骤按能力分发';});
let projectRecording=false;
async function projectRecord(state){if(projectRecording)throw Error('上一项操作仍在保存，请等待回执');if(!projectStep||!projectData?.plan)throw Error('先保存方案并选择步骤');projectRecording=true;$('projectBegin').disabled=true;$('projectFinish').disabled=true;$('projectStatus').textContent='正在保存阶段回执…';try{const r=await api('workflow_project_record',{task_id:projectData.task_ref.object_id,task_revision:projectData.task_ref.revision,stage_id:projectStep.id,state,result:$('projectResult').value,native_locator:$('projectLocator').value,actual_model:'current_host'});projectData.plan=r.plan;projectRender();$('projectStatus').textContent=state==='started'?'已记录开始，当前GPT继续执行；没有再次启动GPT':'公开结果已保存为Evidence；独立验收另计'}catch(e){$('projectStatus').textContent='保存失败：'+e.message;throw e}finally{projectRecording=false;$('projectBegin').disabled=false;$('projectFinish').disabled=false}}
$('projectBegin').onclick=guarded(()=>projectRecord('started'));$('projectFinish').onclick=guarded(()=>projectRecord('completed'));

const batchControls=document.createElement('div');batchControls.innerHTML='<label>已冻结批次 <input id="flowBatch" placeholder="明确冻结的批次目录"></label><button id="flowBatchSelect">切换到已冻结批次</button><p id="flowBatchCurrent"></p>';$('flowStatus').before(batchControls);$('flowBatchSelect').onclick=guarded(async()=>{await api('workflow_select_batch',{directory:$('flowBatch').value.trim()});await flowLoad();$('flowBatchCurrent').textContent='当前批次：'+flowState.batch_directory;});
